SistemaTCC\Model\Semestre:
    type: entity
    table: semestre
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            length: 25
        dataInicio:
            type: datetime
        dataFim:
            type: datetime
        tipo:
            type: integer
    manyToOne:
        campus:
            targetEntity: Campus
            joinColumn:
                name: campus_id
                referencedColumnName: id
